spring:
  datasource:
    url: jdbc:postgresql://ec2-174-129-255-72.compute-1.amazonaws.com:5432/d6cio5mhdnfjb?user=ywrymfqgydpxlj&password=06457a82a66733ca2c6af36dc58ea626bc02c2974ca5bd544130f29ea344ef03&sslmode=require
    username:
    password: